name: pottery_devtools_extension
description: "A Flutter web app for the package:pottery DevTools extension."
publish_to: 'none'
version: 0.0.2

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter

  devtools_app_shared: ^0.1.0
  devtools_extensions: ^0.1.0
  vm_service: ^14.3.0

  collection: ^1.19.0
  custom_text: ^1.4.4
  grab: ^1.0.0-dev.1
  highlight: ^0.7.0
  two_dimensional_scrollables: ^0.0.6

  pottery:
    path: ../pottery

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
