name: pottery_devtools_extension
description: "Pottery DevTools Extension"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter

  devtools_app_shared: ^0.4.0
  devtools_extensions: ^0.4.0
  vm_service: ^14.3.0

  collection: ^1.19.0
  custom_text: ^2.0.4
  grab: ^1.0.2
  two_dimensional_scrollables: ^0.3.7

  pottery:
    path: ../pottery

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
