name: pottery
description: "Utility widgets for Pot in Flutter, automatically managing the lifetime of objects based on the widget lifecycle."
version: 0.4.3
repository: https://github.com/kaboc/pot

topics:
  - dependency-injection

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter

  pot: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

screenshots:
  - description: 'DevTools extension'
    path: screenshots/devtools_extension.jpg
