name: pot
description: An easy and safe DI (Dependency Injection) solution for Dart with support for scoping.
version: 0.8.0
repository: https://github.com/kaboc/pot

topics:
  - dependency-injection

environment:
  sdk: ^3.6.2

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.5
