name: pot
description: A simple and type-safe dependency injection (DI) package, designed for easy scoping and testing.
version: 0.9.0
repository: https://github.com/kaboc/pot

topics:
  - dependency-injection

environment:
  sdk: ^3.6.2

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.5
